spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tihai?serverTimezone=Asia/Shanghai
    username:          #username
    password:         #password
  cloud:
    nacos:
      discovery:
        server-addr:    #127.0.0.1:8848/nacos
        namespace:    #命名空间
  application:
    name: super-auto

dubbo:
  application:
    name: dubbo-super-auto
  registry:
    address:   ##Nacos地址  nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.tihai.service.dubbo
  consumer:
    timeout: 10000

cors:
  allow:
    origins:
      - "http://localhost:3030"  #允许跨域的域名


large:
  model:
    qwen-api-key:  #通义千问api-key

tiku:
  settings:
    endpoints:
        - name:  #示例local,icodef,buguake,wanneng，不填写默认使用所有免费题库
          token: 
        - name: 
          token:


