enable-service-registry: false   #k控制Nacos注册配置,Dubbo注册
spring:
  datasource:
    url: jdbc:mysql://www.xxtmooc.com:3306/tihai?serverTimezone=Asia/Shanghai
    username: root
    password: dc515141b3db4599
  cloud:
    nacos:
      discovery:
        enabled: ${enable-service-registry}
        server-addr: nacos.xxtmooc.com:8848/nacos
        namespace: 6bc0fc78-bcce-408f-94ca-0b18e16212af
        register-enabled: ${enable-service-registry}
  application:
    name: super-auto

dubbo:
  application:
    name: dubbo-super-auto
  config-center:
    enabled: ${enable-service-registry}
  metadata-report:
    enabled: ${enable-service-registry}
  registry:
    register: ${enable-service-registry}
    address: nacos://nacos.xxtmooc.com:8848
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.tihai.service.dubbo
  consumer:
    timeout: 10000

cors:
  allow:
    origins:
      - "http://localhost:3030"  #允许跨域的域名
      - "http://www.xtmooc.com"


custom:
  thread-pool:
    core-size: 5
    max-size: 10
    keep-alive: 60
    queue-capacity: 100
    thread-name-prefix: "priority-pool-"
    allow-core-thread-timeout: true


study:
  chaoxing:
    speed: 3
